### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by H3rmit** [TheCodeForge/syzitus#14]
Could you please explain how to setup a clone with GoDaddy? Or just link an existing video of how to do it. Thank you;

**Comment by H3rmit** [comment]
> 

I basically just want to run my own site like this one. If I could just download the files and put them on the server I would but it seems to be a tad more complicated than that.

**Comment by TheCodeForge** [comment]
It won't work with static/shared hosting due to not being a static site and requiring a fair amount of infrastructure (database, image storage, etc) but I am working on a setup guide. Making Ruqqus/Syzitus easier to fork and launch was always one of my goals for the Syzitus project (and I've also been rewriting code to allow for such a setup guide as well)

**Comment by TheCodeForge** [comment]
https://syzitus.com/+Syzitus/post/1wn/guide-to-running-syzitus
